default: &default
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 4
  username: root
  password: "password"
  host: 127.0.0.1
  template: template_gis
  gis_schema_name: gis_tmp

development: &development
  <<: *default
  database: ethnicchic2_old

test: &test
  <<: *default
  database: default_test

production: &production
  <<: *default
  database: default_production

mysql_data_source: &pii
  hostname: localhost
  port: 3306
  username: root
  password: "password"
  database: ethnicchic_old
  socket: /var/run/mysqld/mysqld.sock

mysql2psql:
  mysql:
    <<: *pii

  destination:
    production:
      <<: *production
    test:
      <<: *test
    development:
      <<: *development


  # If suppress_data is true, only the schema definition will be exported/migrated, and not the data
  suppress_data: false

  # If suppress_ddl is true, only the data will be exported/imported, and not the schema
  suppress_ddl: false

  # If force_truncate is true, forces a table truncate before table loading
  force_truncate: false

  preserve_order: false

  dump_file_directory: /tmp

  clear_schema: true
